language: node_js
sudo: false

node_js:
- "6"
- "8"
- "10"

git:
  depth: false

script:
- if [[ "$TRAVIS_NODE_VERSION" == 6 ]]; then npm test; fi
- if [[ "$TRAVIS_NODE_VERSION" == 8 ]]; then npm test; fi
- if [[ "$TRAVIS_NODE_VERSION" == 10 ]]; then npm test; npm run cover:coveralls; fi