language: node_js
sudo: false

node_js:
- "8"
- "10"
- "11"

cache: npm

git:
  depth: false

script:
- if [[ "$TRAVIS_NODE_VERSION" == 8 ]]; then npm test; fi
- if [[ "$TRAVIS_NODE_VERSION" == 10 ]]; then npm test; fi
- if [[ "$TRAVIS_NODE_VERSION" == 11 ]]; then npm test; npm run cover:coveralls; fi
