name: nkeys.js

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [master]

jobs:
  test:
    name: ${{ matrix.config.kind }} ${{ matrix.config.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.2.0]
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: checkout nkeys
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: setup deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: lint
        run: deno fmt --check src/*.ts test/*.ts

      - name: Test
        env:
          TMPDIR: ${{ runner.temp }}
          CI: true
        run: deno test --failfast

      - name: build nkeys.mjs
        run: deno bundle src/mod.ts nkeys.mjs

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          startsWith(github.ref, 'refs/tags/') &&
          !startsWith(github.ref, 'refs/tags/std/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            nkeys.mjs
          draft: true
